### ISSUE TITLE
ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

### ISSUE THREAD

**Issue by jrinvictus** [IBM/AIX360#46]
I'm working through the Credit Approval Tutorial, 3. Loan Officer: Prototypical explanations for HELOC use case.

When I run the line of code:

(Data, x_train, x_test, y_train_b, y_test_b) = heloc.split()

I get the error:

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

Any idea on how I can get around this error?

**Comment by vijay-arya** [comment]
@jrinvictus Can you please clone the latest version (and do a pip install of aix360) and check if you still encounter this issue. 

The error might have been caused due to two different versions of the heloc dataset in which the ordering of columns was different (RiskPerformance was the first column in one and the last column in the other). The data processing code is now independent of this ordering. Hope this helps. Thanks.

**Comment by jrinvictus** [comment]
I updated the heloc_dataset.py file on my end with the most recent and that appears to have fixed it.  

I noticed another error on line 76 of the file:

                 '..','data','heloc_data')

The '..' was throwing an error for me saying it couldn't find the heloc data file.  When i removed the '..' everything works fine.
